services:
  - type: web
    name: bot-comparer-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
